-- drop objects
drop table d241_cliente cascade constraints;
drop table d241_tipo_prodotto cascade constraints;
drop table d241_prodotto cascade constraints;
drop table d241_vendita cascade constraints;

-- create tables
create table d241_cliente (
    id                             number generated by default on null as identity 
                                   constraint d241_cliente_id_pk primary key,
    cliente                        varchar2(30 char)
                                   constraint d241_cliente_cliente_unq unique not null,
    zona_cliente                   varchar2(10 char) not null
)
;

create table d241_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d241_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(30 char)
                                   constraint d241_tipo_prodo_tipo_prodo_unq unique not null
)
;

create table d241_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d241_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d241_prodotto_tipo_prodotto_fk
                                   references d241_tipo_prodotto not null,
    prodotto                       varchar2(30 char)
                                   constraint d241_prodotto_prodotto_unq unique not null
)
;

-- table index
create index d241_prodotto_i1 on d241_prodotto (tipo_prodotto_id);

create table d241_vendita (
    id                             number generated by default on null as identity 
                                   constraint d241_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d241_vendita_cliente_id_fk
                                   references d241_cliente not null,
    prodotto_id                    number
                                   constraint d241_vendita_prodotto_id_fk
                                   references d241_prodotto not null,
    data                           date not null,
    quantita                       number not null,
    importo                        number not null
)
;

-- table index
create index d241_vendita_i1 on d241_vendita (cliente_id);
create index d241_vendita_i122 on d241_vendita (prodotto_id);

-- load data
 
-- Generated by Quick SQL Martedì Gennaio 24, 2023  10:02:37
 
/*
cliente
  cliente vc30 /nn /unique
  zona_cliente vc10 /nn

tipo_prodotto
  tipo_prodotto vc30 /nn /unique

prodotto
  prodotto vc30 /nn /unique
  tipo_prodotto_id /nn

vendita
  cliente_id /nn
  prodotto_id /nn
  data d /nn
  quantita num /nn
  importo num /nn
#ondelete:restrict
#drop: true

# settings = { prefix: "D241", onDelete: "RESTRICT", semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/
