-- drop objects
drop table d241_ruolo_tipo_prodotto cascade constraints;

-- create tables
create table d241_ruolo_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d241_ruolo_tipo_pr_id_pk primary key,
    ruolo                          varchar2(30 char)
                                   constraint d241_ruolo_tipo_pr_ruolo_unq unique not null,
    tipo_prodotto                  varchar2(200 char)
)
;

-- load data
 
-- Generated by Quick SQL Giovedì Gennaio 26, 2023  18:32:05
 
/*
ruolo_tipo_prodotto
  ruolo vc30 /nn /unique
  tipo_prodotto vc200 
#drop:true

# settings = { prefix: "D241", semantics: "CHAR", drop: true, language: "EN", APEX: true }
*/
