-- create tables
create table d14_tipo_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d14_tipo_prodotto_id_pk primary key,
    tipo_prodotto                  varchar2(50 char)
                                   constraint d14_tipo_prodot_tipo_prodo_unq unique not null,
    gruppo                         varchar2(50 char) not null
)
;

create table d14_prodotto (
    id                             number generated by default on null as identity 
                                   constraint d14_prodotto_id_pk primary key,
    tipo_prodotto_id               number
                                   constraint d14_prodotto_tipo_prodotto_fk
                                   references d14_tipo_prodotto not null,
    prodotto                       varchar2(50 char)
                                   constraint d14_prodotto_prodotto_unq unique not null,
    prezzo_acquisto                number not null,
    prezzo_vendita                 number not null
)
;

-- table index
create index d14_prodotto_i1 on d14_prodotto (tipo_prodotto_id);

create table d14_cliente (
    id                             number generated by default on null as identity 
                                   constraint d14_cliente_id_pk primary key,
    cliente                        varchar2(50 char)
                                   constraint d14_cliente_cliente_unq unique not null,
    zona                           varchar2(10 char) not null
)
;

create table d14_fornitore (
    id                             number generated by default on null as identity 
                                   constraint d14_fornitore_id_pk primary key,
    fornitore                      varchar2(50 char)
                                   constraint d14_fornitore_fornitore_unq unique not null,
    zona                           varchar2(50 char) not null
)
;

create table d14_acquisto (
    id                             number generated by default on null as identity 
                                   constraint d14_acquisto_id_pk primary key,
    fornitore_id                   number
                                   constraint d14_acquisto_fornitore_id_fk
                                   references d14_fornitore not null,
    prodotto_id                    number
                                   constraint d14_acquisto_prodotto_id_fk
                                   references d14_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d14_acquisto_i1 on d14_acquisto (fornitore_id);
create index d14_acquisto_i142 on d14_acquisto (prodotto_id);

create table d14_vendita (
    id                             number generated by default on null as identity 
                                   constraint d14_vendita_id_pk primary key,
    cliente_id                     number
                                   constraint d14_vendita_cliente_id_fk
                                   references d14_cliente not null,
    prodotto_id                    number
                                   constraint d14_vendita_prodotto_id_fk
                                   references d14_prodotto not null,
    data                           date not null,
    quantita                       number not null
)
;

-- table index
create index d14_vendita_i1 on d14_vendita (cliente_id);
create index d14_vendita_i192 on d14_vendita (prodotto_id);

-- load data
 
-- Generated by Quick SQL Giovedì Novembre 17, 2022  22:30:56
 
/*
tipo_prodotto
 tipo_prodotto vc50 /nn /unique
 gruppo vc50 /nn

prodotto
  prodotto vc50 /nn /unique
  tipo_prodotto_id /nn
  prezzo acquisto num /nn
  prezzo vendita num /nn

cliente
  cliente vc50 /nn /unique
  zona vc10 /nn

fornitore
  fornitore vc50 /nn /unique
  zona vc50 /nn

acquisto
  data d /nn
  fornitore_id /nn
  prodotto_id /nn
  quantita num /nn

vendita
  data d /nn
  cliente_id  /nn
  prodotto_id /nn
  quantita num /nn

# settings = { prefix: "d14", onDelete: "RESTRICT", semantics: "CHAR", language: "EN", APEX: true }
*/
