-- create tables
create table d182_azienda (
    id                             number generated by default on null as identity 
                                   constraint d182_azienda_id_pk primary key,
    nome                           varchar2(50 char) not null,
    piva                           varchar2(11 char),
    codfis                         varchar2(16 char),
    azienda_yn                     varchar2(1 char) default 'N' constraint d182_azienda_azienda_yn_ck
                                   check (azienda_yn in ('Y','N')) not null,
    descrizione                    varchar2(4000 char)
)
;

-- load data
 
-- Generated by Quick SQL Venerdì Dicembre 02, 2022  12:39:28
 
/*
azienda
  nome vc50 /nn
  piva vc11
  codfis vc16
  azienda_yn /nn /default N
  descrizione vc4000

# settings = { prefix: "D182", semantics: "CHAR", language: "EN", APEX: true }
*/
