-- create tables
create table d151_azienda (
    id                             number generated by default on null as identity 
                                   constraint d151_azienda_id_pk primary key,
    ragione_sociale                varchar2(50 char) not null,
    partita_iva                    varchar2(11 char) not null,
    codice_fiscale                 varchar2(16 char) not null,
    indirizzo                      varchar2(100 char),
    cap                            varchar2(5 char),
    citta                          varchar2(50 char),
    provincia                      varchar2(2 char),
    telefono                       varchar2(50 char),
    email                          varchar2(50 char)
)
;

create table d151_contatto (
    id                             number generated by default on null as identity 
                                   constraint d151_contatto_id_pk primary key,
    azienda_id                     number
                                   constraint d151_contatto_azienda_id_fk
                                   references d151_azienda not null,
    nome                           varchar2(50 char) not null,
    cognome                        varchar2(50 char) not null,
    telefono                       varchar2(50 char) not null,
    email                          varchar2(255 char) not null,
    ruolo                          varchar2(255 char)
)
;

-- table index
create index d151_contatto_i1 on d151_contatto (azienda_id);

-- load data
 
-- Generated by Quick SQL Sabato Novembre 19, 2022  09:34:17
 
/*
azienda
  ragione_sociale vc50 /nn
  partita_iva vc11 /nn
  codice_fiscale vc16 /nn
  indirizzo vc100
  cap vc5
  citta vc50
  provincia vc2
  telefono vc50
  email vc50

contatto
  nome vc50 /nn
  cognome vc50 /nn
  telefono vc50 /nn
  email /nn
  ruolo vc255
  azienda_id /nn

#ondelete: restrict

# settings = { prefix: "D151", onDelete: "RESTRICT", semantics: "CHAR", language: "EN", APEX: true }
*/
