-- create tables
create table d152_dipendente (
    id                             number generated by default on null as identity 
                                   constraint d152_dipendente_id_pk primary key,
    utente                         varchar2(50 char)
                                   constraint d152_dipendente_utente_unq unique not null,
    nominativo                     varchar2(50 char) not null,
    email                          varchar2(255 char) not null,
    telefono                       varchar2(50 char)
)
;

create table d152_tipo_richiesta (
    id                             number generated by default on null as identity 
                                   constraint d152_tipo_richiest_id_pk primary key,
    tipo_richiesta                 varchar2(9 char)
                                   constraint d152_tipo_ric_tipo_richies_unq unique not null
)
;

create table d152_richiesta (
    id                             number generated by default on null as identity 
                                   constraint d152_richiesta_id_pk primary key,
    dipendente_id                  number
                                   constraint d152_richiesta_dipendente_i_fk
                                   references d152_dipendente not null,
    tipo_richiesta_id              number
                                   constraint d152_richiest_tipo_richiest_fk
                                   references d152_tipo_richiesta not null,
    descrizione                    varchar2(100 char) not null,
    data_inizio                    date not null,
    data_fine                      date,
    approvato_yn                   varchar2(1 char) constraint d152_richiesta_approvato_yn_ck
                                   check (approvato_yn in ('Y','N'))
)
;

-- table index
create index d152_richiesta_i1 on d152_richiesta (dipendente_id);
create index d152_richiesta_i92 on d152_richiesta (tipo_richiesta_id);

-- load data
-- load data
 
insert into d152_tipo_richiesta (
    id,
    tipo_richiesta
) values (
    1,
    'MALATTIA'
);

insert into d152_tipo_richiesta (
    id,
    tipo_richiesta
) values (
    2,
    'FERIE'
);

insert into d152_tipo_richiesta (
    id,
    tipo_richiesta
) values (
    3,
    'PERMESSO'
);

insert into d152_tipo_richiesta (
    id,
    tipo_richiesta
) values (
    4,
    'SMART'
);

insert into d152_tipo_richiesta (
    id,
    tipo_richiesta
) values (
    5,
    'TRASFERTA'
);

commit;

alter table d152_tipo_richiesta
modify id generated always as identity restart start with 6;
 
 
-- Generated by Quick SQL Sabato Novembre 19, 2022  10:58:11
 
/*
dipendente
  utente vc50 /nn /unique
  nominativo vc50 /nn
  email /nn
  telefono vc50

tipo_richiesta /insert 5
  tipo_richiesta vc30 /nn /values MALATTIA, FERIE, PERMESSO, SMART, TRASFERTA /unique

richiesta
  dipendente_id /nn
  tipo_richiesta_id /nn
  descrizione vc100 /nn
  data_inizio d /nn
  data_fine d 
  approvato_yn 
#ondelete: restrict

# settings = { prefix: "D152", onDelete: "RESTRICT", semantics: "CHAR", language: "EN", APEX: true }
*/
