-- create tables
create table d155_dipendente (
    id                             number generated by default on null as identity 
                                   constraint d155_dipendente_id_pk primary key,
    dipendente                     varchar2(4000 char)
                                   constraint d155_dipendente_dipendente_unq unique not null,
    tariffa                        number not null
)
;

create table d155_cliente (
    id                             number generated by default on null as identity 
                                   constraint d155_cliente_id_pk primary key,
    cliente                        varchar2(50 char)
                                   constraint d155_cliente_cliente_unq unique not null
)
;

create table d155_commessa (
    id                             number generated by default on null as identity 
                                   constraint d155_commessa_id_pk primary key,
    commessa                       varchar2(6 char)
                                   constraint d155_commessa_commessa_unq unique not null
)
;

create table d155_attivita (
    id                             number generated by default on null as identity 
                                   constraint d155_attivita_id_pk primary key,
    dipendente_id                  number
                                   constraint d155_attivita_dipendente_id_fk
                                   references d155_dipendente not null,
    cliente_id                     number
                                   constraint d155_attivita_cliente_id_fk
                                   references d155_cliente not null,
    commessa_id                    number
                                   constraint d155_attivita_commessa_id_fk
                                   references d155_commessa not null,
    data                           date not null,
    ore                            number not null
)
;

-- table index
create index d155_attivita_i1 on d155_attivita (cliente_id);
create index d155_attivita_i112 on d155_attivita (commessa_id);
create index d155_attivita_i123 on d155_attivita (dipendente_id);

-- load data
-- load data
 
insert into d155_commessa (
    id,
    commessa
) values (
    1,
    'COMM01'
);

insert into d155_commessa (
    id,
    commessa
) values (
    2,
    'COMM02'
);

insert into d155_commessa (
    id,
    commessa
) values (
    3,
    'COMM03'
);

insert into d155_commessa (
    id,
    commessa
) values (
    4,
    'COMM04'
);

insert into d155_commessa (
    id,
    commessa
) values (
    5,
    'COMM05'
);

commit;

alter table d155_commessa
modify id generated always as identity restart start with 6;
 
 
-- Generated by Quick SQL Domenica Novembre 20, 2022  23:32:02
 
/*
dipendente
  dipendente /nn /unique
  tariffa num /nn 

cliente
  cliente vc50 /nn /unique

commessa /insert 5
  commessa vc30 /nn /values COMM01, COMM02, COMM03, COMM04, COMM05 /unique

attivita
  dipendente_id /nn
  cliente_id /nn
  commessa_id vc100 /nn
  data d /nn
  ore num /nn

#ondelete: restrict

# settings = { prefix: "D155", onDelete: "RESTRICT", semantics: "CHAR", language: "EN", APEX: true }
*/
